<template>
	<div
		class="text-3xl capitalize loader fixed bg-black text-white w-full h-full top-0 left-0 z-[999999] flex justify-center items-center"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			xmlns:xlink="http://www.w3.org/1999/xlink"
			style="
				margin: auto;
				background: none;
				display: block;
				shape-rendering: auto;
			"
			width="100px"
			height="100px"
			viewBox="0 0 100 100"
			preserveAspectRatio="xMidYMid"
		>
			<circle
				cx="50"
				cy="50"
				fill="none"
				stroke="#ffffff"
				stroke-width="10"
				r="35"
				stroke-dasharray="164.93361431346415 56.97787143782138"
			>
				<animateTransform
					attributeName="transform"
					type="rotate"
					repeatCount="indefinite"
					dur="1s"
					values="0 50 50;360 50 50"
					keyTimes="0;1"
				></animateTransform>
			</circle>
			<!-- [ldio] generated by https://loading.io/ -->
		</svg>
	</div>
</template>

<script>
import axios from "axios";
export default {
	name: "pageLoader",
	methods: {
		loading() {
			axios.get("/api/articles", {
				headers: {
					Authorization: "Nn123123"
				}
			}).then((response) => {
				if (response) {
					document.querySelector(".loader").style.display =
						"none";
					document.body.style.overflow = "auto";
				}
			});
		}
	},
	mounted() {
		document.body.style.overflow = "hidden";
		window.addEventListener("load", this.loading());
	}
};
</script>

<style></style>
